version: '3.8'
services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./services/api:/app
    depends_on:
      - redis
      - ollama
    env_file:
      - ./services/api/.env

  frontend:
    image: node:18
    working_dir: /frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - REACT_APP_API_URL=http://api:8000
    depends_on:
      - api

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  redis_data:
  grafana_data: